image: python:3.12.2-slim

stages:
  - build
  - test
  - deploy

dev-job:
  stage: build
  before_script:
    - python -m venv venv
    - source ./venv/bin/activate
  script:
    - pip install -r requirements.txt
    - pip list
    - python app.py &
  artifacts:
    paths:
      - venv
  only:
    - TradeLogic

smoke-test:
  stage: test
  before_script:
    - apt update -y
    - apt install -y curl
    - source ./venv/bin/activate
    - python app.py &
  script:
    - echo "Testing execution"
    - sleep 2
    - echo "slept"
    - curl 127.0.0.1:5001
  needs:
    - flake-test
  only:
    - TradeLogic

flake-test:
  stage: test
  before_script:
    - pip install flake8
    - source ./venv/bin/activate
  script:
    - flake8 . --exclude=venv --ignore=E402,E203,W503 --output-file=flake8-report.txt
  artifacts:
    paths:
      - flake8-results
      - flaskenv
    when: always
  only:
    - TradeLogic

stage-job:
  stage: deploy
  before_script:
    - apt update -y
    - apt install -y curl
    - apt install -y openssh-client
    - echo "***********"
    - echo "$EC2_SSH_PEM" > ./pk.pem
    - chmod 400 ./pk.pem
  script:
    - echo "Delivery"
    - ssh -o StrictHostKeyChecking=no -i ./pk.pem ubuntu@"$EC2_PUBLIC_IP" 'cd /home/ubuntu/code/trade-turbo && git checkout TradeLogic && git pull origin TradeLogic && git reset --hard HEAD && rm -rf venv && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && pip install gunicorn && sudo systemctl restart trade-turbo.service'
  after_script:
    - echo "Testing AWS deployment"
    - sleep 30
    - curl "$EC2_PUBLIC_IP":5001
  only:
    - TradeLogic