image: python:3.12.2-slim

stages:
  - build
  - test
  - deploy

dev-job:
  stage: build
  before_script:
    - python -m venv venv
    - source ./venv/bin/activate
  script:
    - pip install -r requirements.txt
    - pip list
    - python app.py &
  artifacts:
    paths:
      - flaskenv
  only:
    - main

smoke-test:
  stage: test
  before_script:
    - apt update -y
    - apt install -y curl
    - source ./flaskenv/bin/activate
    - python app.py &
  script:
    - echo "Testing execution"
    - sleep 2
    - echo "slept"
    - curl 127.0.0.1:5001
  needs:
    - flake-test
  only:
    - main

flake-test:
  stage: test
  before_script:
    - source ./flaskenv/bin/activate
  script:
    - flake8 --format=html --htmldir=flake8-results/
  artifacts:
    paths:
      - flake8-results
      - flaskenv
    when: always
  only:
    - main

stage-job:
  stage: deploy
  before_script:
    - apt update -y
    - apt install -y curl
    - apt install -y openssh-client
    - echo "***********"
    - echo "$EC2_SSH_PEM" > ./pk.pem
    - chmod 400 ./pk.pem
  script:
    - echo "Delivery"
    - ssh -v -o StrictHostKeyChecking=no -i ./pk.pem ubuntu@[YOUR_IP_ADDRESS] 'cd /home/ubuntu/[YOUR_STOCKIFY_LOCATION] && git fetch origin main && git reset --hard origin/main && sudo systemctl restart clstat'
  after_script:
    - echo "Testing AWS deployment"
    - sleep 30
    - curl [YOUR_IP_ADDRESS]:5001
  only:
    - main